language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: npm@scispike.com
  api_key:
    secure: uAHyGhP/qJF7cr+nGYpVpIdE7iza2CJG38eG7GBNNkmXAm+6ERJ+J1pWGOgUJnO43C452fgwFHWMJNuw2uJRVh9laQUy+xob2VzKNlnj2grosCM1XXDxYVeHaSebWRM0kCr1CeHxEUymeQwHbBEQhepdFCRrHlRG7iC9Mu4teAAV/GzlMHgEbSWUch15ARYeM9DqNgZzuknHRlYmi2DX3YA2UGOIxSKSYLcfX3ZBR3shaaai+v11pHZuEuLMj0gPtq/OqXUW9ZSTb3FZ/c76Dc/MM93LIzR1UMpO4DxgP3k0EXBMhPwJimgEtWGkmPQ4GFWh/xtPGaPFd8QyJoqHiD9s1BxN+GBDGRVQc2xpF907SfZUEKwC4MIQs9V/AtlBPe+MVKnLM2sqwIzGQ5WXSro9i7JlcOYroM/ooxaI/J1DAu56xonVulaZAd7udlSf5zClVBGVe0a+BvAPNi4c8Tihc4lXc0vpUo3NfEMXpmsYo6uKzGNHlNrTXZ7/iNgykgLQFJWqdfJSPQXwEYO5Yvniq1IVJE5YCLBH9k0hyeXEYeEpjPI/dR3xgDh/skhVqxEGrMIj4Xujxds2M1HbhHPc3lABEzlqmEtV3JvZdbBndOokETlqUD0fdOxBA92o7MNqaKprDqocvdXt98UYd1+XJNdMVOWFnMYWPSML2A8=
  on:
    tags: true
    all_branches: false
